language: objective-c
osx_image: mavericks

rvm:
  - "2.0.0; export CEDAR_SDK_VERSION=6.1 #"
  - "2.0.0; export CEDAR_SDK_VERSION=7.0 #"
  - "2.0.0; export CEDAR_SDK_VERSION=7.1 #"

env:
  matrix:
    - CEDAR_SDK_RUNTIME_VERSION="5.1"
    - CEDAR_SDK_RUNTIME_VERSION="6.0"
    - CEDAR_SDK_RUNTIME_VERSION="6.1"
    - CEDAR_SDK_RUNTIME_VERSION="7.0"
    - CEDAR_SDK_RUNTIME_VERSION="7.1"

script: rake
